// truffle.js
const { readFileSync } = require('fs')
const LoomTruffleProvider = require('loom-truffle-provider')

const chainId    = 'default'
const writeUrl   = 'http://127.0.0.1:46658/rpc'
const readUrl    = 'http://127.0.0.1:46658/query'

// ./privateKey file contains a base64 encoded key generated by the command:
// loom genkey -a publicKey -k privateKey
const privateKey = readFileSync('./dev_privateKey', 'utf-8')

const loomTruffleProvider = new LoomTruffleProvider(chainId, writeUrl, readUrl, privateKey)

// Create 10 extra accounts, useful for tests
loomTruffleProvider.createExtraAccounts(10)

module.exports = {
    networks: {
        loom_dapp_chain: {
            provider: loomTruffleProvider,
            network_id: '*'
        }
    }
};